### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by WinggedPhantom** [CommunityBuilt/HuskyCrates-Sponge#2]
* Ability to configure the "key" for the crate - support for modded items.
* Display of what the crates contains - left clicking on crate - single chest GUI with chances and the slots not taken up blanked with gray glass pane.
* Configure the block of the crate or be able to set a block as a crate rather than give the crate
* Ability to give multiple keys at the same time - /crate key <crate id> [player] <number of keys> - If no number provided default to only 1.
* Run multiple commands instead of just one
* Block Placement of Crate Keys (If placeable once they can be configured)

**Comment by WinggedPhantom** [comment]
* Run multiple commands instead of just one

**Comment by WinggedPhantom** [comment]
* Block Placement of Crate Keys (If placeable once they can be configured)

**Comment by KasperFranz** [comment]
Can I get you to make single issues instead of only having 1?

It is way easier to track if it is in single issues :)

**Comment by WinggedPhantom** [comment]
My bad, forgot I could edit the first one. Fixed.

**Comment by KasperFranz** [comment]
Well, I want you to make an issue on each of your topics instead of having this one issue.

Since i can then close the issues when I have done them
